services:
  - type: web
    name: movie-recommendation-system
    runtime: docker
    repo: https://github.com/maneesh255/movie-recommendation-system
    branch: main
    autoDeployTrigger: commit
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/movies
    envVars:
      - key: PORT
        value: 10000
